-- Limpeza de tabelas antigas (cuidado, isso apaga os dados existentes)
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.preferences CASCADE;
DROP TABLE IF EXISTS public.alerts CASCADE;
DROP TABLE IF EXISTS public.readings CASCADE;
DROP TABLE IF EXISTS public.iot_devices CASCADE;
DROP TABLE IF EXISTS public.environments CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 1. Users table
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'client',
    lgpd_accepted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- Insert default admin user
INSERT INTO public.users (email, password_hash, name, role, lgpd_accepted)
VALUES ('admin@energy.com', '$2b$12$K1R2T5B.E2p.GkM.G./wzua4T9l2h8S5Y2w0F3s3N4C4I.B5xU', 'Admin User', 'admin', TRUE)
ON CONFLICT (email) DO NOTHING;

-- 2. Environments table
CREATE TABLE public.environments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT,
    active BOOLEAN DEFAULT TRUE
);

-- 3. IoT Devices table
CREATE TABLE public.iot_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    environment_id BIGINT REFERENCES public.environments(id) ON DELETE SET NULL,
    type TEXT DEFAULT 'sensor',
    status TEXT DEFAULT 'online',
    last_seen TIMESTAMPTZ,
    mqtt_topic TEXT
);

-- 4. Readings table
CREATE TABLE public.readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT REFERENCES public.iot_devices(device_id) ON DELETE CASCADE,
    environment_id BIGINT REFERENCES public.environments(id) ON DELETE CASCADE,
    temperature NUMERIC,
    humidity NUMERIC,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- 5. Alerts table
CREATE TABLE public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT REFERENCES public.iot_devices(device_id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    resolved BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- 6. Preferences table
CREATE TABLE public.preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    units TEXT DEFAULT 'celsius',
    update_interval INTEGER DEFAULT 5,
    favorite_devices TEXT 
);

-- 7. Audit Logs
CREATE TABLE public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc', now())
);
